/**
 * generated by Xtext 2.38.0
 */
package org.xtext.simplepdl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.simplepdl.myDsl.MyDslPackage;
import org.xtext.simplepdl.myDsl.Resource;
import org.xtext.simplepdl.myDsl.WorkDefinition;
import org.xtext.simplepdl.myDsl.WorkSequence;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl#getStartDate <em>Start Date</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl#getEndDate <em>End Date</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl#getLinksToSuccessor <em>Links To Successor</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl#getLinksToPredecessor <em>Links To Predecessor</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl#getResource <em>Resource</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WorkDefinitionImpl extends ProcessElementImpl implements WorkDefinition
{
  /**
   * The default value of the '{@link #getDuration() <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected static final int DURATION_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDuration() <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected int duration = DURATION_EDEFAULT;

  /**
   * The default value of the '{@link #getStartDate() <em>Start Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartDate()
   * @generated
   * @ordered
   */
  protected static final String START_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStartDate() <em>Start Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartDate()
   * @generated
   * @ordered
   */
  protected String startDate = START_DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getEndDate() <em>End Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndDate()
   * @generated
   * @ordered
   */
  protected static final String END_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEndDate() <em>End Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndDate()
   * @generated
   * @ordered
   */
  protected String endDate = END_DATE_EDEFAULT;

  /**
   * The cached value of the '{@link #getLinksToSuccessor() <em>Links To Successor</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinksToSuccessor()
   * @generated
   * @ordered
   */
  protected EList<WorkSequence> linksToSuccessor;

  /**
   * The cached value of the '{@link #getLinksToPredecessor() <em>Links To Predecessor</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinksToPredecessor()
   * @generated
   * @ordered
   */
  protected EList<WorkSequence> linksToPredecessor;

  /**
   * The cached value of the '{@link #getResource() <em>Resource</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResource()
   * @generated
   * @ordered
   */
  protected EList<Resource> resource;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorkDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.WORK_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDuration()
  {
    return duration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDuration(int newDuration)
  {
    int oldDuration = duration;
    duration = newDuration;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WORK_DEFINITION__DURATION, oldDuration, duration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStartDate()
  {
    return startDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStartDate(String newStartDate)
  {
    String oldStartDate = startDate;
    startDate = newStartDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WORK_DEFINITION__START_DATE, oldStartDate, startDate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEndDate()
  {
    return endDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEndDate(String newEndDate)
  {
    String oldEndDate = endDate;
    endDate = newEndDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WORK_DEFINITION__END_DATE, oldEndDate, endDate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkSequence> getLinksToSuccessor()
  {
    if (linksToSuccessor == null)
    {
      linksToSuccessor = new EObjectResolvingEList<WorkSequence>(WorkSequence.class, this, MyDslPackage.WORK_DEFINITION__LINKS_TO_SUCCESSOR);
    }
    return linksToSuccessor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkSequence> getLinksToPredecessor()
  {
    if (linksToPredecessor == null)
    {
      linksToPredecessor = new EObjectResolvingEList<WorkSequence>(WorkSequence.class, this, MyDslPackage.WORK_DEFINITION__LINKS_TO_PREDECESSOR);
    }
    return linksToPredecessor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Resource> getResource()
  {
    if (resource == null)
    {
      resource = new EObjectContainmentEList<Resource>(Resource.class, this, MyDslPackage.WORK_DEFINITION__RESOURCE);
    }
    return resource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.WORK_DEFINITION__RESOURCE:
        return ((InternalEList<?>)getResource()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.WORK_DEFINITION__DURATION:
        return getDuration();
      case MyDslPackage.WORK_DEFINITION__START_DATE:
        return getStartDate();
      case MyDslPackage.WORK_DEFINITION__END_DATE:
        return getEndDate();
      case MyDslPackage.WORK_DEFINITION__LINKS_TO_SUCCESSOR:
        return getLinksToSuccessor();
      case MyDslPackage.WORK_DEFINITION__LINKS_TO_PREDECESSOR:
        return getLinksToPredecessor();
      case MyDslPackage.WORK_DEFINITION__RESOURCE:
        return getResource();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.WORK_DEFINITION__DURATION:
        setDuration((Integer)newValue);
        return;
      case MyDslPackage.WORK_DEFINITION__START_DATE:
        setStartDate((String)newValue);
        return;
      case MyDslPackage.WORK_DEFINITION__END_DATE:
        setEndDate((String)newValue);
        return;
      case MyDslPackage.WORK_DEFINITION__LINKS_TO_SUCCESSOR:
        getLinksToSuccessor().clear();
        getLinksToSuccessor().addAll((Collection<? extends WorkSequence>)newValue);
        return;
      case MyDslPackage.WORK_DEFINITION__LINKS_TO_PREDECESSOR:
        getLinksToPredecessor().clear();
        getLinksToPredecessor().addAll((Collection<? extends WorkSequence>)newValue);
        return;
      case MyDslPackage.WORK_DEFINITION__RESOURCE:
        getResource().clear();
        getResource().addAll((Collection<? extends Resource>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.WORK_DEFINITION__DURATION:
        setDuration(DURATION_EDEFAULT);
        return;
      case MyDslPackage.WORK_DEFINITION__START_DATE:
        setStartDate(START_DATE_EDEFAULT);
        return;
      case MyDslPackage.WORK_DEFINITION__END_DATE:
        setEndDate(END_DATE_EDEFAULT);
        return;
      case MyDslPackage.WORK_DEFINITION__LINKS_TO_SUCCESSOR:
        getLinksToSuccessor().clear();
        return;
      case MyDslPackage.WORK_DEFINITION__LINKS_TO_PREDECESSOR:
        getLinksToPredecessor().clear();
        return;
      case MyDslPackage.WORK_DEFINITION__RESOURCE:
        getResource().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.WORK_DEFINITION__DURATION:
        return duration != DURATION_EDEFAULT;
      case MyDslPackage.WORK_DEFINITION__START_DATE:
        return START_DATE_EDEFAULT == null ? startDate != null : !START_DATE_EDEFAULT.equals(startDate);
      case MyDslPackage.WORK_DEFINITION__END_DATE:
        return END_DATE_EDEFAULT == null ? endDate != null : !END_DATE_EDEFAULT.equals(endDate);
      case MyDslPackage.WORK_DEFINITION__LINKS_TO_SUCCESSOR:
        return linksToSuccessor != null && !linksToSuccessor.isEmpty();
      case MyDslPackage.WORK_DEFINITION__LINKS_TO_PREDECESSOR:
        return linksToPredecessor != null && !linksToPredecessor.isEmpty();
      case MyDslPackage.WORK_DEFINITION__RESOURCE:
        return resource != null && !resource.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (duration: ");
    result.append(duration);
    result.append(", startDate: ");
    result.append(startDate);
    result.append(", endDate: ");
    result.append(endDate);
    result.append(')');
    return result.toString();
  }

} //WorkDefinitionImpl
