/*
 * generated by Xtext 2.38.0
 */
package org.xtext.simplepdl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimplePDLScopeProvider extends DelegatingScopeProvider {
}
