/**
 * generated by Xtext 2.38.0
 */
package org.xtext.simplepdl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.simplepdl.myDsl.ProcessElement;
import org.xtext.simplepdl.myDsl.Resource;
import org.xtext.simplepdl.myDsl.WorkDefinition;
import org.xtext.simplepdl.services.SimplePDLGrammarAccess;

@SuppressWarnings("all")
public class SimplePDLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SimplePDLGrammarAccess _simplePDLGrammarAccess;

  protected void _format(final org.xtext.simplepdl.myDsl.Process process, @Extension final IFormattableDocument document) {
    EList<ProcessElement> _processElements = process.getProcessElements();
    for (final ProcessElement processElement : _processElements) {
      document.<ProcessElement>format(processElement);
    }
  }

  protected void _format(final WorkDefinition workDefinition, @Extension final IFormattableDocument document) {
    EList<Resource> _resource = workDefinition.getResource();
    for (final Resource resource : _resource) {
      document.<Resource>format(resource);
    }
  }

  @XbaseGenerated
  public void format(final Object workDefinition, final IFormattableDocument document) {
    if (workDefinition instanceof XtextResource) {
      _format((XtextResource)workDefinition, document);
      return;
    } else if (workDefinition instanceof WorkDefinition) {
      _format((WorkDefinition)workDefinition, document);
      return;
    } else if (workDefinition instanceof org.xtext.simplepdl.myDsl.Process) {
      _format((org.xtext.simplepdl.myDsl.Process)workDefinition, document);
      return;
    } else if (workDefinition instanceof EObject) {
      _format((EObject)workDefinition, document);
      return;
    } else if (workDefinition == null) {
      _format((Void)null, document);
      return;
    } else if (workDefinition != null) {
      _format(workDefinition, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(workDefinition, document).toString());
    }
  }
}
