/*
 * generated by Xtext 2.38.0
 */
package org.xtext.simplepdl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl.ui.internal.MydslActivator;

public class SimplePDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("org.xtext.simplepdl.SimplePDL");
	}

}
