/**
 * generated by Xtext 2.38.0
 */
package org.xtext.simplepdl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Humain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplepdl.myDsl.Humain#getRole <em>Role</em>}</li>
 * </ul>
 *
 * @see org.xtext.simplepdl.myDsl.MyDslPackage#getHumain()
 * @model
 * @generated
 */
public interface Humain extends Resource
{
  /**
   * Returns the value of the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' attribute.
   * @see #setRole(String)
   * @see org.xtext.simplepdl.myDsl.MyDslPackage#getHumain_Role()
   * @model
   * @generated
   */
  String getRole();

  /**
   * Sets the value of the '{@link org.xtext.simplepdl.myDsl.Humain#getRole <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' attribute.
   * @see #getRole()
   * @generated
   */
  void setRole(String value);

} // Humain
