/**
 * generated by Xtext 2.38.0
 */
package org.xtext.simplepdl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Materiel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplepdl.myDsl.Materiel#getQuantite <em>Quantite</em>}</li>
 * </ul>
 *
 * @see org.xtext.simplepdl.myDsl.MyDslPackage#getMateriel()
 * @model
 * @generated
 */
public interface Materiel extends Resource
{
  /**
   * Returns the value of the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantite</em>' attribute.
   * @see #setQuantite(int)
   * @see org.xtext.simplepdl.myDsl.MyDslPackage#getMateriel_Quantite()
   * @model
   * @generated
   */
  int getQuantite();

  /**
   * Sets the value of the '{@link org.xtext.simplepdl.myDsl.Materiel#getQuantite <em>Quantite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantite</em>' attribute.
   * @see #getQuantite()
   * @generated
   */
  void setQuantite(int value);

} // Materiel
