/**
 * generated by Xtext 2.38.0
 */
package org.xtext.simplepdl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.simplepdl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/simplepdl/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.simplepdl.myDsl.impl.ProcessImpl <em>Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplepdl.myDsl.impl.ProcessImpl
   * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getProcess()
   * @generated
   */
  int PROCESS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__NAME = 0;

  /**
   * The feature id for the '<em><b>Process Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__PROCESS_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.simplepdl.myDsl.impl.ProcessElementImpl <em>Process Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplepdl.myDsl.impl.ProcessElementImpl
   * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getProcessElement()
   * @generated
   */
  int PROCESS_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_ELEMENT__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Process Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.simplepdl.myDsl.impl.ResourceImpl <em>Resource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplepdl.myDsl.impl.ResourceImpl
   * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getResource()
   * @generated
   */
  int RESOURCE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE__NAME = 0;

  /**
   * The number of structural features of the '<em>Resource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl <em>Work Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl
   * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getWorkDefinition()
   * @generated
   */
  int WORK_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__NAME = PROCESS_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__DESCRIPTION = PROCESS_ELEMENT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__DURATION = PROCESS_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__START_DATE = PROCESS_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__END_DATE = PROCESS_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Links To Successor</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__LINKS_TO_SUCCESSOR = PROCESS_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Links To Predecessor</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__LINKS_TO_PREDECESSOR = PROCESS_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Resource</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__RESOURCE = PROCESS_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Work Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION_FEATURE_COUNT = PROCESS_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.simplepdl.myDsl.impl.WorkSequenceImpl <em>Work Sequence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplepdl.myDsl.impl.WorkSequenceImpl
   * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getWorkSequence()
   * @generated
   */
  int WORK_SEQUENCE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__NAME = PROCESS_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__DESCRIPTION = PROCESS_ELEMENT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__TYPE = PROCESS_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__PREDECESSOR = PROCESS_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Successor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__SUCCESSOR = PROCESS_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Work Sequence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_FEATURE_COUNT = PROCESS_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.simplepdl.myDsl.impl.HumainImpl <em>Humain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplepdl.myDsl.impl.HumainImpl
   * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getHumain()
   * @generated
   */
  int HUMAIN = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HUMAIN__NAME = RESOURCE__NAME;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HUMAIN__ROLE = RESOURCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Humain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HUMAIN_FEATURE_COUNT = RESOURCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.simplepdl.myDsl.impl.MaterielImpl <em>Materiel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplepdl.myDsl.impl.MaterielImpl
   * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getMateriel()
   * @generated
   */
  int MATERIEL = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATERIEL__NAME = RESOURCE__NAME;

  /**
   * The feature id for the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATERIEL__QUANTITE = RESOURCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Materiel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATERIEL_FEATURE_COUNT = RESOURCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.simplepdl.myDsl.WorkSequenceType <em>Work Sequence Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.simplepdl.myDsl.WorkSequenceType
   * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getWorkSequenceType()
   * @generated
   */
  int WORK_SEQUENCE_TYPE = 7;


  /**
   * Returns the meta object for class '{@link org.xtext.simplepdl.myDsl.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process</em>'.
   * @see org.xtext.simplepdl.myDsl.Process
   * @generated
   */
  EClass getProcess();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.Process#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.simplepdl.myDsl.Process#getName()
   * @see #getProcess()
   * @generated
   */
  EAttribute getProcess_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.simplepdl.myDsl.Process#getProcessElements <em>Process Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Process Elements</em>'.
   * @see org.xtext.simplepdl.myDsl.Process#getProcessElements()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_ProcessElements();

  /**
   * Returns the meta object for class '{@link org.xtext.simplepdl.myDsl.ProcessElement <em>Process Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process Element</em>'.
   * @see org.xtext.simplepdl.myDsl.ProcessElement
   * @generated
   */
  EClass getProcessElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.ProcessElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.simplepdl.myDsl.ProcessElement#getName()
   * @see #getProcessElement()
   * @generated
   */
  EAttribute getProcessElement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.ProcessElement#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.simplepdl.myDsl.ProcessElement#getDescription()
   * @see #getProcessElement()
   * @generated
   */
  EAttribute getProcessElement_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.simplepdl.myDsl.Resource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Resource</em>'.
   * @see org.xtext.simplepdl.myDsl.Resource
   * @generated
   */
  EClass getResource();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.Resource#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.simplepdl.myDsl.Resource#getName()
   * @see #getResource()
   * @generated
   */
  EAttribute getResource_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.simplepdl.myDsl.WorkDefinition <em>Work Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Definition</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkDefinition
   * @generated
   */
  EClass getWorkDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkDefinition#getDuration()
   * @see #getWorkDefinition()
   * @generated
   */
  EAttribute getWorkDefinition_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getStartDate <em>Start Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Date</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkDefinition#getStartDate()
   * @see #getWorkDefinition()
   * @generated
   */
  EAttribute getWorkDefinition_StartDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getEndDate <em>End Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Date</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkDefinition#getEndDate()
   * @see #getWorkDefinition()
   * @generated
   */
  EAttribute getWorkDefinition_EndDate();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getLinksToSuccessor <em>Links To Successor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Links To Successor</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkDefinition#getLinksToSuccessor()
   * @see #getWorkDefinition()
   * @generated
   */
  EReference getWorkDefinition_LinksToSuccessor();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getLinksToPredecessor <em>Links To Predecessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Links To Predecessor</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkDefinition#getLinksToPredecessor()
   * @see #getWorkDefinition()
   * @generated
   */
  EReference getWorkDefinition_LinksToPredecessor();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getResource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Resource</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkDefinition#getResource()
   * @see #getWorkDefinition()
   * @generated
   */
  EReference getWorkDefinition_Resource();

  /**
   * Returns the meta object for class '{@link org.xtext.simplepdl.myDsl.WorkSequence <em>Work Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Sequence</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkSequence
   * @generated
   */
  EClass getWorkSequence();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.WorkSequence#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkSequence#getType()
   * @see #getWorkSequence()
   * @generated
   */
  EAttribute getWorkSequence_Type();

  /**
   * Returns the meta object for the reference '{@link org.xtext.simplepdl.myDsl.WorkSequence#getPredecessor <em>Predecessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Predecessor</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkSequence#getPredecessor()
   * @see #getWorkSequence()
   * @generated
   */
  EReference getWorkSequence_Predecessor();

  /**
   * Returns the meta object for the reference '{@link org.xtext.simplepdl.myDsl.WorkSequence#getSuccessor <em>Successor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Successor</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkSequence#getSuccessor()
   * @see #getWorkSequence()
   * @generated
   */
  EReference getWorkSequence_Successor();

  /**
   * Returns the meta object for class '{@link org.xtext.simplepdl.myDsl.Humain <em>Humain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Humain</em>'.
   * @see org.xtext.simplepdl.myDsl.Humain
   * @generated
   */
  EClass getHumain();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.Humain#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role</em>'.
   * @see org.xtext.simplepdl.myDsl.Humain#getRole()
   * @see #getHumain()
   * @generated
   */
  EAttribute getHumain_Role();

  /**
   * Returns the meta object for class '{@link org.xtext.simplepdl.myDsl.Materiel <em>Materiel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Materiel</em>'.
   * @see org.xtext.simplepdl.myDsl.Materiel
   * @generated
   */
  EClass getMateriel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.simplepdl.myDsl.Materiel#getQuantite <em>Quantite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantite</em>'.
   * @see org.xtext.simplepdl.myDsl.Materiel#getQuantite()
   * @see #getMateriel()
   * @generated
   */
  EAttribute getMateriel_Quantite();

  /**
   * Returns the meta object for enum '{@link org.xtext.simplepdl.myDsl.WorkSequenceType <em>Work Sequence Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Work Sequence Type</em>'.
   * @see org.xtext.simplepdl.myDsl.WorkSequenceType
   * @generated
   */
  EEnum getWorkSequenceType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.simplepdl.myDsl.impl.ProcessImpl <em>Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplepdl.myDsl.impl.ProcessImpl
     * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getProcess()
     * @generated
     */
    EClass PROCESS = eINSTANCE.getProcess();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS__NAME = eINSTANCE.getProcess_Name();

    /**
     * The meta object literal for the '<em><b>Process Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__PROCESS_ELEMENTS = eINSTANCE.getProcess_ProcessElements();

    /**
     * The meta object literal for the '{@link org.xtext.simplepdl.myDsl.impl.ProcessElementImpl <em>Process Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplepdl.myDsl.impl.ProcessElementImpl
     * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getProcessElement()
     * @generated
     */
    EClass PROCESS_ELEMENT = eINSTANCE.getProcessElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS_ELEMENT__NAME = eINSTANCE.getProcessElement_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS_ELEMENT__DESCRIPTION = eINSTANCE.getProcessElement_Description();

    /**
     * The meta object literal for the '{@link org.xtext.simplepdl.myDsl.impl.ResourceImpl <em>Resource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplepdl.myDsl.impl.ResourceImpl
     * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getResource()
     * @generated
     */
    EClass RESOURCE = eINSTANCE.getResource();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESOURCE__NAME = eINSTANCE.getResource_Name();

    /**
     * The meta object literal for the '{@link org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl <em>Work Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplepdl.myDsl.impl.WorkDefinitionImpl
     * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getWorkDefinition()
     * @generated
     */
    EClass WORK_DEFINITION = eINSTANCE.getWorkDefinition();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION__DURATION = eINSTANCE.getWorkDefinition_Duration();

    /**
     * The meta object literal for the '<em><b>Start Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION__START_DATE = eINSTANCE.getWorkDefinition_StartDate();

    /**
     * The meta object literal for the '<em><b>End Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION__END_DATE = eINSTANCE.getWorkDefinition_EndDate();

    /**
     * The meta object literal for the '<em><b>Links To Successor</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_DEFINITION__LINKS_TO_SUCCESSOR = eINSTANCE.getWorkDefinition_LinksToSuccessor();

    /**
     * The meta object literal for the '<em><b>Links To Predecessor</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_DEFINITION__LINKS_TO_PREDECESSOR = eINSTANCE.getWorkDefinition_LinksToPredecessor();

    /**
     * The meta object literal for the '<em><b>Resource</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_DEFINITION__RESOURCE = eINSTANCE.getWorkDefinition_Resource();

    /**
     * The meta object literal for the '{@link org.xtext.simplepdl.myDsl.impl.WorkSequenceImpl <em>Work Sequence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplepdl.myDsl.impl.WorkSequenceImpl
     * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getWorkSequence()
     * @generated
     */
    EClass WORK_SEQUENCE = eINSTANCE.getWorkSequence();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_SEQUENCE__TYPE = eINSTANCE.getWorkSequence_Type();

    /**
     * The meta object literal for the '<em><b>Predecessor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE__PREDECESSOR = eINSTANCE.getWorkSequence_Predecessor();

    /**
     * The meta object literal for the '<em><b>Successor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE__SUCCESSOR = eINSTANCE.getWorkSequence_Successor();

    /**
     * The meta object literal for the '{@link org.xtext.simplepdl.myDsl.impl.HumainImpl <em>Humain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplepdl.myDsl.impl.HumainImpl
     * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getHumain()
     * @generated
     */
    EClass HUMAIN = eINSTANCE.getHumain();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HUMAIN__ROLE = eINSTANCE.getHumain_Role();

    /**
     * The meta object literal for the '{@link org.xtext.simplepdl.myDsl.impl.MaterielImpl <em>Materiel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplepdl.myDsl.impl.MaterielImpl
     * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getMateriel()
     * @generated
     */
    EClass MATERIEL = eINSTANCE.getMateriel();

    /**
     * The meta object literal for the '<em><b>Quantite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATERIEL__QUANTITE = eINSTANCE.getMateriel_Quantite();

    /**
     * The meta object literal for the '{@link org.xtext.simplepdl.myDsl.WorkSequenceType <em>Work Sequence Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.simplepdl.myDsl.WorkSequenceType
     * @see org.xtext.simplepdl.myDsl.impl.MyDslPackageImpl#getWorkSequenceType()
     * @generated
     */
    EEnum WORK_SEQUENCE_TYPE = eINSTANCE.getWorkSequenceType();

  }

} //MyDslPackage
