/**
 * generated by Xtext 2.38.0
 */
package org.xtext.simplepdl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.simplepdl.myDsl.WorkDefinition#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.WorkDefinition#getStartDate <em>Start Date</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.WorkDefinition#getEndDate <em>End Date</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.WorkDefinition#getLinksToSuccessor <em>Links To Successor</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.WorkDefinition#getLinksToPredecessor <em>Links To Predecessor</em>}</li>
 *   <li>{@link org.xtext.simplepdl.myDsl.WorkDefinition#getResource <em>Resource</em>}</li>
 * </ul>
 *
 * @see org.xtext.simplepdl.myDsl.MyDslPackage#getWorkDefinition()
 * @model
 * @generated
 */
public interface WorkDefinition extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see org.xtext.simplepdl.myDsl.MyDslPackage#getWorkDefinition_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

  /**
   * Returns the value of the '<em><b>Start Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Date</em>' attribute.
   * @see #setStartDate(String)
   * @see org.xtext.simplepdl.myDsl.MyDslPackage#getWorkDefinition_StartDate()
   * @model
   * @generated
   */
  String getStartDate();

  /**
   * Sets the value of the '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getStartDate <em>Start Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Date</em>' attribute.
   * @see #getStartDate()
   * @generated
   */
  void setStartDate(String value);

  /**
   * Returns the value of the '<em><b>End Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Date</em>' attribute.
   * @see #setEndDate(String)
   * @see org.xtext.simplepdl.myDsl.MyDslPackage#getWorkDefinition_EndDate()
   * @model
   * @generated
   */
  String getEndDate();

  /**
   * Sets the value of the '{@link org.xtext.simplepdl.myDsl.WorkDefinition#getEndDate <em>End Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Date</em>' attribute.
   * @see #getEndDate()
   * @generated
   */
  void setEndDate(String value);

  /**
   * Returns the value of the '<em><b>Links To Successor</b></em>' reference list.
   * The list contents are of type {@link org.xtext.simplepdl.myDsl.WorkSequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links To Successor</em>' reference list.
   * @see org.xtext.simplepdl.myDsl.MyDslPackage#getWorkDefinition_LinksToSuccessor()
   * @model
   * @generated
   */
  EList<WorkSequence> getLinksToSuccessor();

  /**
   * Returns the value of the '<em><b>Links To Predecessor</b></em>' reference list.
   * The list contents are of type {@link org.xtext.simplepdl.myDsl.WorkSequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links To Predecessor</em>' reference list.
   * @see org.xtext.simplepdl.myDsl.MyDslPackage#getWorkDefinition_LinksToPredecessor()
   * @model
   * @generated
   */
  EList<WorkSequence> getLinksToPredecessor();

  /**
   * Returns the value of the '<em><b>Resource</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.simplepdl.myDsl.Resource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource</em>' containment reference list.
   * @see org.xtext.simplepdl.myDsl.MyDslPackage#getWorkDefinition_Resource()
   * @model containment="true"
   * @generated
   */
  EList<Resource> getResource();

} // WorkDefinition
